### ISSUE TITLE
Criando guia para entrar na aplicação

### ISSUE THREAD

**Issue by ServidioEC** [DITGO/2021-2-SiGeD-Doc#21]
#### Descrição
Um dos problemas enfrentados para conseguir logar na aplicação é o sistema de senha temporária utilizado pela aplicação. É preciso configurar alguns passos para receber a senha por e-mail. 

#### Objetivo
Com o objetivo de facilitar o trabalho dos desenvolvedores, decidiu-se criar um guia para lidar com a senha temporária e logar na aplicação.

#### Tarefas
- [x] Adição de documento com o passo a passo.

#### Checklist
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [x] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by DITGO** [comment]
Documento Aprovado
