### ISSUE TITLE
Adequação do Grid de Clientes

### ISSUE THREAD

**Issue by DITGO** [DITGO/2021-2-SiGeD-Doc#7]
Épico: Grid de Clientes

Funcionalidade de listar os clientes com recurso de paginação e pesquisa por nomes e ordenação de colunas.

História de usuário:

Eu, como usuário, desejo que a lista de clientes seja apresentada parcialmente (paginação, aproximadamente 20 clientes por pagina). Considerando que está lista possui mais de 4.000 clientes, está inviabilizando a utilização por conta da lentidão na composição da listagem.

Eu, como usuário, desejo que seja possível consultar em todo banco pelo nome do cliente para realizar filtro na lista de clientes.

Eu, como usuário, desejo que seja possível classificar as colunas da listagem dos clientes por ordem crescente ou decrescente.

**Comment by isabellacgmsa** [comment]
Fazendo a divisão em subtaks, temos:
 - [ ] [Backend] Criar rota para pesquisa por nome 
 - [ ] [Backend] Alterar response do get usuários para paginação
 - [ ] [Backend] Alterar response do get usuários com ordenação

 - [ ] [Frontend] Alterar página para adequar a paginação
 - [ ] [Frontend] Criar componente para pesquisar usuário
 - [ ] [Frontend] Alterar tabela para ordenação
