### ISSUE TITLE
CRUD Patrimonio

### ISSUE THREAD

**Issue by DITGO** [DITGO/2021-2-SiGeD-Doc#8]
Épico: Controle de Patrimonio

Funcionalidade de cadastrar os itens patrimoniais da DPSS contendo nome, descrição e foto.
Funcionalidade de consulta de dados referentes aos itens cadastrados no inventário da DPSS.
Funcionalidade de imprimir os itens cadastrados no inventário da DPSS.

História de usuário:

Eu, como usuário, desejo cadastrar um item ao inventário da unidade.
Eu, como usuário, desejo consultar o inventário patrimonial da DPSS.
Eu, como usuário, desejo gerar o relatório dos itens do inventário patrimonial da DPSS.

**Comment by isadoragalvaoss** [comment]
Issue resolvida no repositório:
https://github.com/DITGO/2021-2-SiGeD-Patrimonio

**Comment by DITGO** [comment]
Ficou incompleto, precisaria ter criado no frontend o acesso a api
